ESX = nil



poleemploi = {   
	Base = { Header = {"commonmenu", "interaction_bgd"}, Color = {color_Green}, HeaderColor = {255, 255, 255}, Title = "Centre Emplois"},
	Data = { currentMenu = "Action", GetPlayerName()},
    Events = {
		onSelected = function(self, _, btn, PMenu, Data, menuData, currentMenu, currentButton, currentBtn, currentSlt, result, slide)
			if self.Data.currentMenu == "Action" then
				TriggerServerEvent('setjob', btn.value)
                ESX.ShowNotification('~b~Vous avez desormais le job ~g~'..btn.name)
			end
		end,     
	}, 
	Menu = { 
		["Action"] = {
			b = {}
		},
	}
}  
 
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')


----
Citizen.CreateThread( function()
	while ESX == nil do
		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
		Citizen.Wait(0)
	end
	while true do
		time = 0

	  local playerpos = GetEntityCoords(PlayerPedId())

    local point = Vdist(playerpos, -267.415, -957.121, 31.223)

	if point <= 1 then
		ESX.ShowHelpNotification('Appuyer sur ~b~[E] ~w~pour acceder au centre de l emploi')
		if IsControlJustPressed(0, 51) then
			poleemploi.Menu["Action"].b = {}

			ESX.TriggerServerCallback('getpoleemploi', function(result)
				for k, v in pairs(result) do
					if v.SecondaryJob == false then
						table.insert(poleemploi.Menu["Action"].b, {name = v.label, value = v.name})
						
					end
					CreateMenu(poleemploi)
					end
					
			end)
			
	end
end
		
       Citizen.Wait(time)
	end
end)
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')

--------------------------ped
Citizen.CreateThread(function()
    local hash = GetHashKey("a_m_y_smartcaspat_01")
    while not HasModelLoaded(hash) do
    RequestModel(hash)
    Wait(20)
    end
    ped = CreatePed("PED_TYPE_CIVFEMALE", "a_m_y_smartcaspat_01", -267.518, -957.375, 30.223, 194.09, true, true)
    SetBlockingOfNonTemporaryEvents(ped, true)
    FreezeEntityPosition(ped, true)
end)

local v1 = vector3(-267.518, -957.375, 32.223)

function Draw3DText(x, y, z, text)
    local onScreen, _x, _y = World3dToScreen2d(x, y, z)
    local p = GetGameplayCamCoords()
    local distance = GetDistanceBetweenCoords(p.x, p.y, p.z, x, y, z, 1)
    local scale = (1 / distance) * 2
    local fov = (1 / GetGameplayCamFov()) * 100
    local scale = scale * fov
    if onScreen then
        SetTextScale(0.0, 0.35)
        SetTextFont(0)
        SetTextProportional(1)
        SetTextColour(255, 255, 255, 255)
        SetTextDropshadow(0, 0, 0, 0, 255)
        SetTextEdge(2, 0, 0, 0, 150)
        SetTextDropShadow()
        SetTextOutline()
        SetTextEntry("STRING")
        SetTextCentre(1)
        AddTextComponentString(text)
        DrawText(_x,_y)
    end
end

local distance = 20

Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
        if Vdist2(GetEntityCoords(PlayerPedId(), false), v1) < distance then
            Draw3DText(v1.x,v1.y,v1.z, "Carl")
        end
    end
end)
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
print('LSLIFECREATOR')
